cold_storage:
  - "fake_cold_dir"
config: tests/config.yaml
design: tests/design.tsv
params:
  libType: ISF
  salmon_index_extra: ' --kmerLen 5 '
  salmon_quant_extra: ' --noBiasLengthThreshold --minAssignedFrags 1 --noEffectiveLengthCorrection
    --noLengthCorrection --fasterMapping --noFragLengthDist --allowDovetail --numPreAuxModelSamples
    0 --numAuxModelSamples 0 '
ref:
  fasta: tests/genome/transcriptome.fasta
  gtf: tests/genome/annot.gtf
singularity_docker_image: docker://continuumio/miniconda3:4.4.10
threads: 1
workdir: tests
workflow:
  aggregate: true
  fastqc: true
  multiqc: true
