---
name: rna-count-salmon
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python==3.9.1
  - conda-forge::pytest==6.2.1
  - conda-forge::datrie==0.8.2
  - conda-forge::git==2.30.0
  - conda-forge::jinja2==2.11.2
  - conda-forge::pygraphviz==1.6
  - conda-forge::flask==1.1.2
  - conda-forge::pandas==1.2.0
  - conda-forge::zlib==1.2.11
  - conda-forge::openssl==1.1.1i
  - conda-forge::networkx==2.5
  - bioconda::snakemake==5.31.1
  - conda-forge::ipython==7.19.0
  - conda-forge::bashlex==0.15
  - conda-forge::black==20.8b1
  - conda-forge::singularity==3.6.4
  - conda-forge::mamba==0.7.6
variables:
  PIPELINE_PREFIX: "."
  SNAKEMAKE_OUTPUT_CACHE: "snakemake/cache"
  PROFILE: ".igr/profile/local"
  SNAKEFILE: "Snakefile"
  PREPARE_CONFIG: scripts/prepare_config.py"
  PREPARE_DESIGN: "scripts/prepare_design.py"
  FASTA: "tests/genome/transcriptome.fasta"
  GTF: "tests/genome/annot.gtf"
