---
name: rna-count-salmon
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python==3.9.1
  - conda-forge::pytest==6.2.1
  - conda-forge::pandas==1.2.0
  - bioconda::snakemake=5.32.2
  - conda-forge::mamba==0.7.6
variables:
  PIPELINE_PREFIX: "."
  SNAKEMAKE_OUTPUT_CACHE: "snakemake/cache"
  PROFILE: ".igr/profile/local"
  SNAKEFILE: "Snakefile"
  PREPARE_CONFIG: scripts/prepare_config.py"
  PREPARE_DESIGN: "scripts/prepare_design.py"
  FASTA: "tests/genome/transcriptome.fasta"
  GTF: "tests/genome/annot.gtf"
