---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 * * 0'

jobs:
  conda_setup:
    name: Conda Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup conda
        run: bash .github/workflows/setup.sh
  pipeline_test:
    name: Pipeline tests
    runs-on: ubuntu-latest
    needs: conda_setup
    steps:
      - uses: actions/checkout@v1
      - name: Setup workflow environment
        run: make conda-tests
      - name: Scripts unit-testing
        run: source "$$(conda info --base)/etc/profile.d/conda.sh" && conda activate && conda activate rna-count-salmon && make all-unit-tests
      - name: Run Cli-wrapper
        run: source "$$(conda info --base)/etc/profile.d/conda.sh" && conda activate && conda activate rna-count-salmon && make test-cli-wrapper-report.html
